package net.chessbuddies.player;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.technovator.api.common.annotations.AutoGeneratedUUID;
import com.technovator.api.common.auditlog.AuditableChild;
import com.technovator.api.common.auditlog.AuditableMain;
import com.technovator.api.common.constants.Views;
import com.technovator.api.common.domain.IdentifiableEntity;

@Entity
@Table(name = "PLAYER_QA")
public class QuestionAnswer implements AuditableChild<String>, IdentifiableEntity<String>{
	@Id
	@Column(name="ID")
	@Schema(description = "Internal ID", required=true)
	@JsonView(value = {Views.List.class})
	@AutoGeneratedUUID
	private String id;
	@Column(name="PLAYER_ID")
	private String playerId;
	@Column(name="Q_CODE")
	private String questionCode;
	@Column(name="QA")
	private String answer;
	public String getPlayerId() {
		return playerId;
	}
	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}
	public String getQuestionCode() {
		return questionCode;
	}
	public void setQuestionCode(String questionCode) {
		this.questionCode = questionCode;
	}
	public String getAnswer() {
		return answer;
	}
	public void setAnswer(String answer) {
		this.answer = answer;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@Override
	@JsonIgnore
	public String getAppObjectType() {
		return this.getClass().getSimpleName();
	}
	@Override
	@JsonIgnore
	public String getName() {
		return questionCode;
	}
	@Override
	@JsonIgnore
	public String getParentId() {
		return playerId;
	}
	@Override
	@JsonIgnore
	public Class<? extends AuditableMain<?>> getParentEntity() {
		return Player.class;
	}

}
